on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.7.0
        with:
          base-image: rwthika/ros2-torch:humble-desktop-full-torch2.5.0
          command: ros2 run instance_segmentation instance_segmentation_node.py
